-- CHIFAA — Supabase schema (Postgres)
-- Safe to run in the Supabase SQL editor. Idempotent-ish: drops/creates its own
-- objects. Bilingual (en/ar) only where an _ar.json exists today; team/partners/
-- home/contact/ai_companion are single-language.
--
-- Model: shared/language-neutral fields live on the parent table; translatable
-- text lives in a *_translations table keyed by (parent_id, lang). Categories are
-- a single source of truth (slug + labels) shared by the admin picker AND the site
-- filters, so the old admin-vs-site category mismatch cannot recur.

-- ------------------------------------------------------------------ helpers ----
create or replace function public.set_updated_at() returns trigger
language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

-- --------------------------------------------------------------- categories ----
create table if not exists public.categories (
  slug      text primary key,
  label_en  text not null,
  label_ar  text not null,
  sort      int  not null default 0
);

-- ------------------------------------------------------------------ articles ----
create table if not exists public.articles (
  id             bigint generated by default as identity primary key,
  slug           text unique not null,
  status         text not null default 'published' check (status in ('draft','published')),
  cover_image    text,
  author         text not null default 'Maha Jouini',
  author_role    text,
  author_image   text,
  category_slugs text[] not null default '{}',   -- FK-by-convention to categories.slug
  read_time      int  not null default 1,
  featured       boolean not null default false,
  published_date date,
  views          int  not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists articles_status_idx on public.articles(status);
create index if not exists articles_published_idx on public.articles(published_date desc);

create table if not exists public.article_translations (
  article_id  bigint references public.articles(id) on delete cascade,
  lang        text not null check (lang in ('en','ar')),
  title       text not null,
  excerpt     text,
  content     text,                              -- HTML body
  tags        text[] not null default '{}',
  ar_edited   boolean not null default false,    -- true = hand-polished AR, don't auto-overwrite
  primary key (article_id, lang)
);

-- -------------------------------------------------------------- team_members ----
create table if not exists public.team_members (
  id          bigint generated by default as identity primary key,
  name        text not null,
  role        text,
  eyebrow     text,
  bio         text,
  image       text,
  email       text,
  linkedin    text,
  twitter     text,
  instagram   text,
  behance     text,
  founder_link boolean not null default false,
  sort        int not null default 0,
  updated_at  timestamptz not null default now()
);

-- ------------------------------------------------------------------ founders ----
create table if not exists public.founders (
  id          bigint generated by default as identity primary key,
  image       text,
  sort        int not null default 0,
  updated_at  timestamptz not null default now()
);
create table if not exists public.founder_translations (
  founder_id  bigint references public.founders(id) on delete cascade,
  lang        text not null check (lang in ('en','ar')),
  name        text not null,
  eyebrow     text,
  subtitle    text,
  intro       text,
  full_bio    text,                              -- HTML
  tags        text[] not null default '{}',
  primary key (founder_id, lang)
);

-- ----------------------------------------------------------- podcast_episodes ----
create table if not exists public.podcast_episodes (
  id            bigint generated by default as identity primary key,
  youtube_url   text,
  published_date date,
  featured      boolean not null default false,
  sort          int not null default 0,
  updated_at    timestamptz not null default now()
);
create table if not exists public.podcast_translations (
  episode_id  bigint references public.podcast_episodes(id) on delete cascade,
  lang        text not null check (lang in ('en','ar')),
  title       text not null,
  description text,
  tag         text,
  primary key (episode_id, lang)
);

-- ------------------------------------------------------------------ partners ----
create table if not exists public.partners (
  id               bigint generated by default as identity primary key,
  name             text not null,
  description      text,
  logo             text,
  logo_url         text,
  fallback_text    text,
  tile_class       text,
  website          text,
  background_color text,
  sort             int not null default 0,
  updated_at       timestamptz not null default now()
);

-- --------------------------------------------------------------- mena_health ----
create table if not exists public.mena_health (
  country_id      text primary key,              -- e.g. 'dza'
  iso2            text,
  flag            text,
  womens_health   jsonb not null default '{}',
  chronic_disease jsonb not null default '{}',
  cervical_cancer jsonb not null default '{}',
  sort            int not null default 0
);
create table if not exists public.mena_translations (
  country_id  text references public.mena_health(country_id) on delete cascade,
  lang        text not null check (lang in ('en','ar')),
  country     text not null,
  primary key (country_id, lang)
);

-- ------------------------------------------------------------------- authors ----
-- Low-priority (articles carry their own author fields); kept for completeness.
create table if not exists public.authors (
  id       bigint generated by default as identity primary key,
  name     text not null,
  role     text,
  image    text,
  bio      text,
  socials  jsonb not null default '{}'
);

-- ------------------------------------------------------------- site_content ----
-- Singletons: about, home, contact, ai_companion. One row per (key, lang).
create table if not exists public.site_content (
  key         text not null,                     -- 'about' | 'home' | 'contact' | 'ai_companion'
  lang        text not null default 'en' check (lang in ('en','ar')),
  data        jsonb not null default '{}',
  updated_at  timestamptz not null default now(),
  primary key (key, lang)
);

-- --------------------------------------------------------- updated_at triggers ----
do $$
declare t text;
begin
  foreach t in array array['articles','team_members','founders','podcast_episodes','partners','site_content']
  loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', t);
  end loop;
end $$;

-- ============================================================== RLS policies ====
-- Public (anon) can READ published content; only authenticated (the admin) writes.
alter table public.categories           enable row level security;
alter table public.articles             enable row level security;
alter table public.article_translations enable row level security;
alter table public.team_members         enable row level security;
alter table public.founders             enable row level security;
alter table public.founder_translations enable row level security;
alter table public.podcast_episodes     enable row level security;
alter table public.podcast_translations enable row level security;
alter table public.partners             enable row level security;
alter table public.mena_health          enable row level security;
alter table public.mena_translations    enable row level security;
alter table public.authors              enable row level security;
alter table public.site_content         enable row level security;

-- Always-public read tables
do $$
declare t text;
begin
  foreach t in array array['categories','article_translations','team_members','founders',
                           'founder_translations','podcast_episodes','podcast_translations',
                           'partners','mena_health','mena_translations','authors','site_content']
  loop
    execute format('drop policy if exists public_read on public.%I', t);
    execute format('create policy public_read on public.%I for select to anon, authenticated using (true)', t);
    execute format('drop policy if exists admin_write on public.%I', t);
    execute format('create policy admin_write on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- Articles: anon sees only published; authenticated sees all + writes.
drop policy if exists public_read_published on public.articles;
create policy public_read_published on public.articles
  for select to anon using (status = 'published');
drop policy if exists admin_read_all on public.articles;
create policy admin_read_all on public.articles
  for select to authenticated using (true);
drop policy if exists admin_write on public.articles;
create policy admin_write on public.articles
  for all to authenticated using (true) with check (true);

-- ============================================================ storage bucket ====
insert into storage.buckets (id, name, public)
values ('images','images', true)
on conflict (id) do update set public = true;

drop policy if exists images_public_read on storage.objects;
create policy images_public_read on storage.objects
  for select to anon, authenticated using (bucket_id = 'images');
drop policy if exists images_admin_write on storage.objects;
create policy images_admin_write on storage.objects
  for all to authenticated using (bucket_id = 'images') with check (bucket_id = 'images');
